In [1]:
import pandas as pd
import pyarrow.parquet as pq


ruta_base = "/home/oscar/budasbi-repos/factored-datathon-2024-voyager/parquet"  # o "ruta/local/a/tus/archivos/"


df = pq.ParquetDataset(ruta_base, use_legacy_dataset=False).read_pandas().to_pandas()

/tmp/ipykernel_5957/179273696.py:8: FutureWarning: Passing 'use_legacy_dataset' is deprecated as of pyarrow 15.0.0 and will be removed in a future version.
  df = pq.ParquetDataset(ruta_base, use_legacy_dataset=False).read_pandas().to_pandas()

   numarts                      count_type  number   object_type  geo_type  \
0       54  CRISISLEX_C03_WELLBEING_HEALTH      19          None         1
1      431                            KILL       3         girls         4
2      431                            KILL       3         girls         4
3        1                           WOUND       2  IDF soldiers         1
4       33              CRISISLEX_T03_DEAD       6          None         1

                        geo_fullname geo_country_code geo_adm1_code  geo_lat  \
0                             Israel               IS            IS  31.5000
1  Southport, Sefton, United Kingdom               UK          UKL8  53.6667
2  Southport, Sefton, United Kingdom               UK          UKL8  53.6667
3                               Iran               IR            IR  32.0000
4                         Bangladesh               BG            BG  24.0000

   geo_long geo_feature_id cameo_event_ids  \
0     34.75             IS      1190918611
1     -3.00       -2608309      1190914795
2     -3.00       -2608309      1190917081
3     53.00             IR      1190914848
4     90.00             BG      1190995174

                                             sources  \
0  wcfcourier.com;mynews4.com;dailyherald.com;rev...
1  tspr.org;weaa.org;wknofm.org;wfae.org;npr.org;...
2  tspr.org;weaa.org;wknofm.org;wfae.org;npr.org;...
3                                    dailymail.co.uk
4  bdnews24.com;pakobserver.net;thedailystar.net;...

                                         source_urls        date
0  https://wcfcourier.com/news/nation-world/israe...  2024-08-05
1  https://www.tspr.org/npr-news/2024-08-04/far-r...  2024-08-05
2  https://www.tspr.org/npr-news/2024-08-04/far-r...  2024-08-05
3  https://www.dailymail.co.uk/news/article-13710...  2024-08-05
4  https://bdnews24.com/media-en/b04c70a8c067<UDI...  2024-08-05

In [2]:
df.head()

,numarts,count_type,number,object_type,geo_type,geo_fullname,geo_country_code,geo_adm1_code,geo_lat,geo_long,geo_feature_id,cameo_event_ids,sources,source_urls,date
0,54,CRISISLEX_C03_WELLBEING_HEALTH,19,None,1,Israel,IS,IS,31.5000,34.75,IS,1190918611,wcfcourier.com;mynews4.com;dailyherald.com;rev...,https://wcfcourier.com/news/nation-world/israe...,2024-08-05
1,431,KILL,3,girls,4,"Southport, Sefton, United Kingdom",UK,UKL8,53.6667,-3.00,-2608309,1190914795,tspr.org;weaa.org;wknofm.org;wfae.org;npr.org;...,https://www.tspr.org/npr-news/2024-08-04/far-r...,2024-08-05
2,431,KILL,3,girls,4,"Southport, Sefton, United Kingdom",UK,UKL8,53.6667,-3.00,-2608309,1190917081,tspr.org;weaa.org;wknofm.org;wfae.org;npr.org;...,https://www.tspr.org/npr-news/2024-08-04/far-r...,2024-08-05
3,1,WOUND,2,IDF soldiers,1,Iran,IR,IR,32.0000,53.00,IR,1190914848,dailymail.co.uk,https://www.dailymail.co.uk/news/article-13710...,2024-08-05
4,33,CRISISLEX_T03_DEAD,6,None,1,Bangladesh,BG,BG,24.0000,90.00,BG,1190995174,bdnews24.com;pakobserver.net;thedailystar.net;...,https://bdnews24.com/media-en/b04c70a8c067<UDI...,2024-08-05